apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-dbgate-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dbgate.pvc.storageRequest }}
  {{- if .Values.dbgate.pvc.storageClassName }}
  storageClassName: {{ .Values.dbgate.pvc.storageClassName }}
  {{- end }}
  {{- if .Values.dbgate.pvc.selector }}
  selector:
    matchLabels:
      {{ .Values.dbgate.pvc.selector }}
  {{- end }}
